service: roa-bot

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  stage: prod

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  scraper:
    handler: handler.scraper
    events:
      - schedule: rate(5 minutes)
